version: '3.8'

services:

  db-project:
    image: postgres
    container_name: project_database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_project
    ports:
      - "5432:5432"
  db_task:
    image: postgres
    container_name: task_database
    restart: always
    environment:
      POSTGRES_USER: task
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_task
    ports:
      - "5433:5432"

    


